### ISSUE TITLE
Meta descriptions are wrong in Events

### ISSUE THREAD

**Issue by alsahawneh** [jordanopensource/portal-web#129]
**Link to Issue on portal-web-lagacy:** https://github.com/jordanopensource/portal-web-legacy/issues/428.

**Describe the bug**
When sharing a link to an event the meta description is incorrect as it shows the title twice instead of a short description

**To Reproduce**

1. Copy the link of an event
2. Paste it in a text box that shows the metadata of links inside it

**Expected behavior**
The title with a short description underneath it

**Screenshots**
![139882771-69ccca7b-2c03-44b5-b988-3c444a29b202](https://user-images.githubusercontent.com/79845228/152674567-528a7f4a-637d-48fc-a8cb-fa4ba26ed55e.png)

**Comment by thread-koder** [comment]
@alsahawneh I couldn't reproduce the issue, as it's not showing me the title twice, did you check if the issue is still there before opening it from the portal-web-legacy repository?

**Comment by alsahawneh** [comment]
@thread-koder I don't rightly know, to be honest, we have moved all open issues that we think no one has worked on them to this repo. Could you please double-check this issue with @mahasneh?

**Comment by thread-koder** [comment]
@alsahawneh I understand but we really should check if we can reproduce the issue before moving the opened issue to here, as we fixed so many issues and bugs while refactoring the code

**Comment by mahasneh** [comment]
This is still not fixed, it still shows the title twice as it's assuming the title to be the meta description rather than the event's description

**Comment by mahasneh** [comment]
Check the FB debugger, e.g.:
![image](https://user-images.githubusercontent.com/7326249/153192624-a824647f-d44c-43d7-940d-e687341f5000.png)

**Comment by thread-koder** [comment]
@mahasneh Thank you for the clarification, I will start working on it right away
